name: e305
description: Browse e926 or e621
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.6.5+439

environment:
  sdk: ">=2.2.8 <3.0.8"

dependencies:
  # adobe_xd: ^0.1.3
  # background_fetch: ^0.5.5
  # bottom_navy_bar: ^5.4.0
  # flutter_data: ^0.3.12
  # flutter_local_notifications: ^1.4.2
  # memoize: ^2.0.0
  # state_persistence: ^0.0.7
  # admob_flutter:
  about:
  auto_size_text:
  autocomplete_textfield:
  cached_network_image:
  carousel_slider:
  cupertino_icons:
  dio:
  dio_http_cache:
  expandable:
  filesize:
  flare_flutter:
  flutter_point_tab_bar:
  flutter:
    sdk: flutter
  flutter_html:
  flutter_json_widget:
  flutter_linkify:
  flutter_markdown:
  flutter_screenutil:
  flutter_staggered_grid_view:
  flutter_sticky_header:
  flutter_whatsnew:
    git:
      url: "https://github.com/fluttercommunity/flutter_whatsnew.git"
  font_awesome_flutter:
  get:
    git:
      url: "https://github.com/jonataslaw/get.git"
  getflutter:
  giffy_dialog:
  google_fonts:
  gradient_widgets:
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  image_gallery_saver:
  intl:
  package_info:
  pagination_view:
  path_provider:
  pedantic:
  permission_handler:
  photo_view:
  preferences:
  shared_preferences:
  synchronized:
  uni_links:
  url_launcher:
  video_box:
  xml2json:
  flutter_advanced_networkimage:

dependency_overrides:
  flutter_svg: ^0.18.0
  xml: ^4.2.0
  chewie:
    git:
      url: https://github.com/brianegan/chewie.git

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_native_splash:
  hive_generator:
#  flutter_test:
#    sdk: flutter

flutter_native_splash:
  image: assets/largeIcon.png
  color: "000000"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: ".\\assets\\E305_Logo2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/instagram_like.flr
    - CHANGELOG.md
    - assets/E305_Logo2.png

