/// Flutter icons CustomIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData e621 = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData apple_touch_icon_trans_whited =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData apple_touch_icon_trans_whited_inverse =
      IconData(0xe802, fontFamily: _kFontFam);
}
